import { Feature } from "../interface";

export const FEATURES: Feature[][] = [
  [
    { id: "1", name: "Çağrı Ses Kaydı", state: "right" },
    { id: "2", name: "Mesai Saatleri Ayarlaması", state: "middle" },
    { id: "3", name: "Standart Sesli Karşılama IVR", state: "left" },
    { id: "4", name: "Dijital Fax", state: "right" },
    { id: "5", name: "Görünen No Değiştirme", state: "right" },
    { id: "6", name: "Tek Tıkla Arama", state: "right" },
    { id: "7", name: "Zil Grubu", state: "right" },
    { id: "8", name: "DID Desteği", state: "right" },
    { id: "9", name: "Kara Liste Özelliği", state: "right" },
    { id: "10", name: "Çağrı Bekleme", state: "right" },
    { id: "11", name: "Otomatik Karşılama", state: "right" },
    { id: "12", name: "Sevis Seviyesi Ölçümü", state: "right" },
    { id: "13", name: "Güvenlik Duvarı", state: "right" },
  ],
  [
    { id: "14", name: "Bekleme Müziği", state: "right" },
    { id: "15", name: "Gösterge Paneli", state: "right" },
    { id: "16", name: "Gelişmiş API Desteği", state: "right" },
    { id: "17", name: "Anket Modülü", state: "right" },
    { id: "18", name: "Arayanı Önceliklendirme", state: "right" },
    { id: "19", name: "Arayanı Önceliklendirme", state: "right" },
    { id: "20", name: "Hafızalı Çağrı Aktarımı", state: "right" },
    { id: "21", name: "Canlı Operatör Paneli", state: "right" },
    { id: "22", name: "Maliyet Göstergesi", state: "right" },
    { id: "23", name: "TTS Entegrasyonu", state: "right" },
    { id: "24", name: "Kaçan Çağrı Raporu", state: "right" },
    { id: "25", name: "Otomatik Raporlar", state: "right" },
    { id: "26", name: "Beni Takip Et", state: "right" },
  ],
  [
    { id: "27", name: "Çoklu Tele Konferans", state: "right" },
    { id: "28", name: "Rahatsız Etmeyin", state: "right" },
    { id: "29", name: "Bulut Tabanlı İletişim", state: "right" },
    { id: "30", name: "Çağrı Transferi", state: "right" },
    { id: "31", name: "Kaçan Çağrı Bildirimi", state: "right" },
    { id: "32", name: "Çağrı Sırası Bildirimi", state: "right" },
    { id: "33", name: "Arayan No Gösterme", state: "right" },
    { id: "34", name: "Sesli Posta VM", state: "right" },
    { id: "35", name: "Sesli ve Yazılı Mesaj", state: "right" },
    { id: "36", name: "API Anahtarı", state: "right" },
    { id: "37", name: "Gelişmiş Çağrı Analizi", state: "right" },
  ],
];
